### PR TITLE
fix NameError handling in expression code

### PR DESCRIPTION
**Pull request by shazarivf**
Fixes https://github.com/lmfit/asteval/issues/129

@newville could you take a look please?

### CODE REVIEW

**Comment by newville** [comment]
@shazarivf Thanks!  Looking at this some more, I might add a few more changes in the error handling too.

**Comment by shazarivf** [comment]
@newville Thanks! Can a release be made with this fix anytime soon?

**Comment by shazarivf** [comment]
@newville could you tell me when a release can be made with this change? It's a blocker for us.

**Comment by newville** [comment]
@shazarivf 1.0.2 has been tagged and pushed to PyPI.   I don't usually consider each bug fix to require a release.  FWIW, asking for a release of open-source software twice in two days is probably not going to be a winning strategy very often.

**Comment by shazarivf** [comment]
@newville thanks for making an exception. Yeah I get it.

**Pull request merged**
